[package]
name = "jot"
version = "0.1.0"
description = "Fast, keyboard-first markdown notes"
authors = ["happynut"]
license = "MIT"
repository = "https://github.com/happy-nut/jot"
edition = "2021"
rust-version = "1.77.2"

[lib]
name = "jot_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2" }

[dependencies]
serde = { version = "1", features = ["derive"] }
tauri = { version = "2" }
tauri-plugin-global-shortcut = "2"

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
strip = true
